[package]
name = "crunchy-cli-core"
authors = ["Crunchy Labs Maintainers"]
version = "3.0.0-dev.13"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.2", features = ["derive", "string"] }
chrono = "0.4"
crunchyroll-rs = { version = "0.3.6", features = ["dash-stream"] }
ctrlc = "3.2"
dirs = "5.0"
derive_setters = "0.1"
fs2 = "0.4"
indicatif = "0.17"
lazy_static = "1.4"
log = { version = "0.4", features = ["std"] }
num_cpus = "1.15"
regex = "1.8"
reqwest = { version = "0.11", default-features = false, features = ["socks"] }
sanitize-filename = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_plain = "1.0"
shlex = "1.1"
tempfile = "3.5"
terminal_size = "0.2"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread", "time"] }
sys-locale = "0.3"

[build-dependencies]
chrono = "0.4"
